sudo: required

services:
  - docker

install:
  - docker build -t dockertestimage .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run -e ci_env -ti dockertestimage /bin/bash -c
      "cd micromagneticmodel;
      python3 -m pytest --cov=./ --cov-config .coveragerc;
      bash <(curl -s https://codecov.io/bash) -t 0d9dd293-acd4-4368-b081-88a560ebe35a"

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF